"""
    AMPAREX Rest API Documentation

    This is the description of the AMPAREX Rest API. All REST calls plus the corresponding data model are described in this documentation. Direct calls to the server are possible over this page.&lt;br/&gt;Following steps are needed to use the API:&lt;br/&gt;&lt;br/&gt;1. Get the alias identifier of your login account from AMPAREX Software (Branch office administration) -&gt; Service accounts -&gt; your service account -&gt; copy alias token)&lt;br/&gt;2. Please use the login URL /alias/{alias}/login under section \"Login\" below with your credentials to get a valid bearer token.&lt;br/&gt;3. Copy bearer token from login response&lt;br/&gt;3. Then click \"Authorize\" on the top of this page&lt;br/&gt;4. Insert into the field \"value\": \"Bearer {Your Bearer token}\" (without {}) for example \"Bearer 334d34d3dgh5tz5h5h\"&lt;br/&gt;4. Click Authorize&lt;br/&gt;5. Bearer token will be automatically used in the header for every following API call.&lt;br/&gt;6. Now you are ready to use the API&lt;br/&gt;&lt;br/&gt;See also [documentation](https://manual.amparex.com/display/HAN/AMPAREX+API) for help&lt;br/&gt;&lt;br/&gt;Documentation of all the used fields and objects is at the bottom of this page called \"Models\"  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amparex
from amparex.api.login_api import LoginApi  # noqa: E501


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_user_using_post(self):
        """Test case for change_user_using_post

        Relogin or change user with pincode, use alias from AMPAREX service account. Each consecutive request, other than login, grants a new security-token with a default validity of 60 minutes. Use the new token to avoid expiration.  # noqa: E501
        """
        pass

    def test_get_sec_token_using_post(self):
        """Test case for get_sec_token_using_post

        Login with user and password, use alias from AMPAREX service account. Each consecutive request, other than login, grants a new security-token with a default validity of 60 minutes. Use the new token to avoid expiration.The use of URL parameters is a securirty isse, whenever possible use the header parameters!  # noqa: E501
        """
        pass

    def test_get_sec_token_using_post1(self):
        """Test case for get_sec_token_using_post1

        Login with AMPAREX user, password and branchId, use alias from AMPAREX service account. Each consecutive request, other than login, grants a new security-token with a default validity of 60 minutes. Use the new token to avoid expiration. This login can be used to switch branches for a current logged-in AMPAREX user.  # noqa: E501
        """
        pass

    def test_invalidate_sec_token_using_post(self):
        """Test case for invalidate_sec_token_using_post

        Logout, invalidate security token  # noqa: E501
        """
        pass

    def test_who_am_i_using_get(self):
        """Test case for who_am_i_using_get

        Get information about the current userlogin  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
