"""
    AMPAREX Rest API Documentation

    This is the description of the AMPAREX Rest API. All REST calls plus the corresponding data model are described in this documentation. Direct calls to the server are possible over this page.&lt;br/&gt;Following steps are needed to use the API:&lt;br/&gt;&lt;br/&gt;1. Get the alias identifier of your login account from AMPAREX Software (Branch office administration) -&gt; Service accounts -&gt; your service account -&gt; copy alias token)&lt;br/&gt;2. Please use the login URL /alias/{alias}/login under section \"Login\" below with your credentials to get a valid bearer token.&lt;br/&gt;3. Copy bearer token from login response&lt;br/&gt;3. Then click \"Authorize\" on the top of this page&lt;br/&gt;4. Insert into the field \"value\": \"Bearer {Your Bearer token}\" (without {}) for example \"Bearer 334d34d3dgh5tz5h5h\"&lt;br/&gt;4. Click Authorize&lt;br/&gt;5. Bearer token will be automatically used in the header for every following API call.&lt;br/&gt;6. Now you are ready to use the API&lt;br/&gt;&lt;br/&gt;See also [documentation](https://manual.amparex.com/display/HAN/AMPAREX+API) for help&lt;br/&gt;&lt;br/&gt;Documentation of all the used fields and objects is at the bottom of this page called \"Models\"  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import amparex
from amparex.api.treatments_api import TreatmentsApi  # noqa: E501


class TestTreatmentsApi(unittest.TestCase):
    """TreatmentsApi unit test stubs"""

    def setUp(self):
        self.api = TreatmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sales_order_using_post(self):
        """Test case for create_sales_order_using_post

        Create a new sales order  # noqa: E501
        """
        pass

    def test_get_doctor_for_treatment_using_get(self):
        """Test case for get_doctor_for_treatment_using_get

        Get the assigned doctor for the treatment  # noqa: E501
        """
        pass

    def test_get_document_binary_using_get1(self):
        """Test case for get_document_binary_using_get1

        Get document of treatment as blob  # noqa: E501
        """
        pass

    def test_get_therapeutics_treatment_using_get(self):
        """Test case for get_therapeutics_treatment_using_get

        Get one specific therapeutics treatment by id  # noqa: E501
        """
        pass

    def test_get_treatment_invoices_using_get(self):
        """Test case for get_treatment_invoices_using_get

        Get all documents of all types for one specific treatment  # noqa: E501
        """
        pass

    def test_get_treatment_using_get(self):
        """Test case for get_treatment_using_get

        Get one specific treatment by id  # noqa: E501
        """
        pass

    def test_search_documents_using_post1(self):
        """Test case for search_documents_using_post1

        Get a list of treatment documents (without binary)  # noqa: E501
        """
        pass

    def test_search_treatments_using_post(self):
        """Test case for search_treatments_using_post

        Get a list of treatments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
