"""
    AMPAREX Rest API Documentation

    This is the description of the AMPAREX Rest API. All REST calls plus the corresponding data model are described in this documentation. Direct calls to the server are possible over this page.&lt;br/&gt;Following steps are needed to use the API:&lt;br/&gt;&lt;br/&gt;1. Get the alias identifier of your login account from AMPAREX Software (Branch office administration) -&gt; Service accounts -&gt; your service account -&gt; copy alias token)&lt;br/&gt;2. Please use the login URL /alias/{alias}/login under section \"Login\" below with your credentials to get a valid bearer token.&lt;br/&gt;3. Copy bearer token from login response&lt;br/&gt;3. Then click \"Authorize\" on the top of this page&lt;br/&gt;4. Insert into the field \"value\": \"Bearer {Your Bearer token}\" (without {}) for example \"Bearer 334d34d3dgh5tz5h5h\"&lt;br/&gt;4. Click Authorize&lt;br/&gt;5. Bearer token will be automatically used in the header for every following API call.&lt;br/&gt;6. Now you are ready to use the API&lt;br/&gt;&lt;br/&gt;See also [documentation](https://manual.amparex.com/display/HAN/AMPAREX+API) for help&lt;br/&gt;&lt;br/&gt;Documentation of all the used fields and objects is at the bottom of this page called \"Models\"  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from amparex.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from amparex.exceptions import ApiAttributeError


def lazy_import():
    from amparex.model.article_item import ArticleItem
    from amparex.model.branch_reduced import BranchReduced
    from amparex.model.glasses_configuration import GlassesConfiguration
    from amparex.model.invoice import Invoice
    from amparex.model.predefined_property_reduced import PredefinedPropertyReduced
    from amparex.model.refraction_report import RefractionReport
    from amparex.model.staff_reduced import StaffReduced
    from amparex.model.treatment import Treatment
    globals()['ArticleItem'] = ArticleItem
    globals()['BranchReduced'] = BranchReduced
    globals()['GlassesConfiguration'] = GlassesConfiguration
    globals()['Invoice'] = Invoice
    globals()['PredefinedPropertyReduced'] = PredefinedPropertyReduced
    globals()['RefractionReport'] = RefractionReport
    globals()['StaffReduced'] = StaffReduced
    globals()['Treatment'] = Treatment


class GlassesCare(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'abc_mets': (str,),  # noqa: E501
            'azg': (float,),  # noqa: E501
            'bleft': (float,),  # noqa: E501
            'branch': (BranchReduced,),  # noqa: E501
            'bright': (float,),  # noqa: E501
            'center_thickness_optimized': (bool,),  # noqa: E501
            'customer_id': (str,),  # noqa: E501
            'design_type': (str,),  # noqa: E501
            'df_left': (float,),  # noqa: E501
            'df_right': (float,),  # noqa: E501
            'distance_mid': (float,),  # noqa: E501
            'distance_near': (float,),  # noqa: E501
            'dn_left': (float,),  # noqa: E501
            'dn_right': (float,),  # noqa: E501
            'end_date': (date,),  # noqa: E501
            'facet_form': (str,),  # noqa: E501
            'form_height': (float,),  # noqa: E501
            'form_length': (float,),  # noqa: E501
            'frame': (ArticleItem,),  # noqa: E501
            'frame_fit': (float,),  # noqa: E501
            'frame_text': (str,),  # noqa: E501
            'glas_left': (GlassesConfiguration,),  # noqa: E501
            'glas_right': (GlassesConfiguration,),  # noqa: E501
            'glasses_pass_printed': (bool,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'initials': (str,),  # noqa: E501
            'insets_left': (float,),  # noqa: E501
            'insets_right': (float,),  # noqa: E501
            'invoices': ([Invoice],),  # noqa: E501
            'komplettbrille': (bool,),  # noqa: E501
            'mindestranddicke': (float,),  # noqa: E501
            'modified': (datetime,),  # noqa: E501
            'my_style_code': (str,),  # noqa: E501
            'near_profile': (str,),  # noqa: E501
            'near_vision_behaviour': (str,),  # noqa: E501
            'notice': (str,),  # noqa: E501
            'order_glasses': (bool,),  # noqa: E501
            'ordered_glas_left': (GlassesConfiguration,),  # noqa: E501
            'ordered_glas_right': (GlassesConfiguration,),  # noqa: E501
            'own_frame': (bool,),  # noqa: E501
            'price_frame': (float,),  # noqa: E501
            'price_glas_left': (float,),  # noqa: E501
            'price_glas_right': (float,),  # noqa: E501
            'progression_length_left': (float,),  # noqa: E501
            'progression_length_right': (float,),  # noqa: E501
            'refraction_glasses': (RefractionReport,),  # noqa: E501
            'refraction_objective': (RefractionReport,),  # noqa: E501
            'refraction_prescription': (RefractionReport,),  # noqa: E501
            'remote_edging': (bool,),  # noqa: E501
            'scheibenwinkel': (float,),  # noqa: E501
            'staff': (StaffReduced,),  # noqa: E501
            'start_date': (date,),  # noqa: E501
            'treatment': (Treatment,),  # noqa: E501
            'treatment_head_id': (str,),  # noqa: E501
            'treatment_number': (str,),  # noqa: E501
            'type': (PredefinedPropertyReduced,),  # noqa: E501
            'vorneigung': (float,),  # noqa: E501
            'weight': (float,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'abc_mets': 'abcMets',  # noqa: E501
        'azg': 'azg',  # noqa: E501
        'bleft': 'bleft',  # noqa: E501
        'branch': 'branch',  # noqa: E501
        'bright': 'bright',  # noqa: E501
        'center_thickness_optimized': 'centerThicknessOptimized',  # noqa: E501
        'customer_id': 'customerID',  # noqa: E501
        'design_type': 'designType',  # noqa: E501
        'df_left': 'dfLeft',  # noqa: E501
        'df_right': 'dfRight',  # noqa: E501
        'distance_mid': 'distanceMid',  # noqa: E501
        'distance_near': 'distanceNear',  # noqa: E501
        'dn_left': 'dnLeft',  # noqa: E501
        'dn_right': 'dnRight',  # noqa: E501
        'end_date': 'endDate',  # noqa: E501
        'facet_form': 'facetForm',  # noqa: E501
        'form_height': 'formHeight',  # noqa: E501
        'form_length': 'formLength',  # noqa: E501
        'frame': 'frame',  # noqa: E501
        'frame_fit': 'frameFit',  # noqa: E501
        'frame_text': 'frameText',  # noqa: E501
        'glas_left': 'glasLeft',  # noqa: E501
        'glas_right': 'glasRight',  # noqa: E501
        'glasses_pass_printed': 'glassesPassPrinted',  # noqa: E501
        'id': 'id',  # noqa: E501
        'initials': 'initials',  # noqa: E501
        'insets_left': 'insetsLeft',  # noqa: E501
        'insets_right': 'insetsRight',  # noqa: E501
        'invoices': 'invoices',  # noqa: E501
        'komplettbrille': 'komplettbrille',  # noqa: E501
        'mindestranddicke': 'mindestranddicke',  # noqa: E501
        'modified': 'modified',  # noqa: E501
        'my_style_code': 'myStyleCode',  # noqa: E501
        'near_profile': 'nearProfile',  # noqa: E501
        'near_vision_behaviour': 'nearVisionBehaviour',  # noqa: E501
        'notice': 'notice',  # noqa: E501
        'order_glasses': 'orderGlasses',  # noqa: E501
        'ordered_glas_left': 'orderedGlasLeft',  # noqa: E501
        'ordered_glas_right': 'orderedGlasRight',  # noqa: E501
        'own_frame': 'ownFrame',  # noqa: E501
        'price_frame': 'priceFrame',  # noqa: E501
        'price_glas_left': 'priceGlasLeft',  # noqa: E501
        'price_glas_right': 'priceGlasRight',  # noqa: E501
        'progression_length_left': 'progressionLengthLeft',  # noqa: E501
        'progression_length_right': 'progressionLengthRight',  # noqa: E501
        'refraction_glasses': 'refractionGlasses',  # noqa: E501
        'refraction_objective': 'refractionObjective',  # noqa: E501
        'refraction_prescription': 'refractionPrescription',  # noqa: E501
        'remote_edging': 'remoteEdging',  # noqa: E501
        'scheibenwinkel': 'scheibenwinkel',  # noqa: E501
        'staff': 'staff',  # noqa: E501
        'start_date': 'startDate',  # noqa: E501
        'treatment': 'treatment',  # noqa: E501
        'treatment_head_id': 'treatmentHeadID',  # noqa: E501
        'treatment_number': 'treatmentNumber',  # noqa: E501
        'type': 'type',  # noqa: E501
        'vorneigung': 'vorneigung',  # noqa: E501
        'weight': 'weight',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """GlassesCare - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            abc_mets (str): [optional]  # noqa: E501
            azg (float): [optional]  # noqa: E501
            bleft (float): [optional]  # noqa: E501
            branch (BranchReduced): [optional]  # noqa: E501
            bright (float): [optional]  # noqa: E501
            center_thickness_optimized (bool): [optional]  # noqa: E501
            customer_id (str): [optional]  # noqa: E501
            design_type (str): [optional]  # noqa: E501
            df_left (float): [optional]  # noqa: E501
            df_right (float): [optional]  # noqa: E501
            distance_mid (float): [optional]  # noqa: E501
            distance_near (float): [optional]  # noqa: E501
            dn_left (float): [optional]  # noqa: E501
            dn_right (float): [optional]  # noqa: E501
            end_date (date): [optional]  # noqa: E501
            facet_form (str): [optional]  # noqa: E501
            form_height (float): [optional]  # noqa: E501
            form_length (float): [optional]  # noqa: E501
            frame (ArticleItem): [optional]  # noqa: E501
            frame_fit (float): [optional]  # noqa: E501
            frame_text (str): [optional]  # noqa: E501
            glas_left (GlassesConfiguration): [optional]  # noqa: E501
            glas_right (GlassesConfiguration): [optional]  # noqa: E501
            glasses_pass_printed (bool): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            initials (str): [optional]  # noqa: E501
            insets_left (float): [optional]  # noqa: E501
            insets_right (float): [optional]  # noqa: E501
            invoices ([Invoice]): [optional]  # noqa: E501
            komplettbrille (bool): [optional]  # noqa: E501
            mindestranddicke (float): [optional]  # noqa: E501
            modified (datetime): [optional]  # noqa: E501
            my_style_code (str): [optional]  # noqa: E501
            near_profile (str): [optional]  # noqa: E501
            near_vision_behaviour (str): [optional]  # noqa: E501
            notice (str): [optional]  # noqa: E501
            order_glasses (bool): [optional]  # noqa: E501
            ordered_glas_left (GlassesConfiguration): [optional]  # noqa: E501
            ordered_glas_right (GlassesConfiguration): [optional]  # noqa: E501
            own_frame (bool): [optional]  # noqa: E501
            price_frame (float): [optional]  # noqa: E501
            price_glas_left (float): [optional]  # noqa: E501
            price_glas_right (float): [optional]  # noqa: E501
            progression_length_left (float): [optional]  # noqa: E501
            progression_length_right (float): [optional]  # noqa: E501
            refraction_glasses (RefractionReport): [optional]  # noqa: E501
            refraction_objective (RefractionReport): [optional]  # noqa: E501
            refraction_prescription (RefractionReport): [optional]  # noqa: E501
            remote_edging (bool): [optional]  # noqa: E501
            scheibenwinkel (float): [optional]  # noqa: E501
            staff (StaffReduced): [optional]  # noqa: E501
            start_date (date): [optional]  # noqa: E501
            treatment (Treatment): [optional]  # noqa: E501
            treatment_head_id (str): [optional]  # noqa: E501
            treatment_number (str): [optional]  # noqa: E501
            type (PredefinedPropertyReduced): [optional]  # noqa: E501
            vorneigung (float): [optional]  # noqa: E501
            weight (float): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """GlassesCare - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            abc_mets (str): [optional]  # noqa: E501
            azg (float): [optional]  # noqa: E501
            bleft (float): [optional]  # noqa: E501
            branch (BranchReduced): [optional]  # noqa: E501
            bright (float): [optional]  # noqa: E501
            center_thickness_optimized (bool): [optional]  # noqa: E501
            customer_id (str): [optional]  # noqa: E501
            design_type (str): [optional]  # noqa: E501
            df_left (float): [optional]  # noqa: E501
            df_right (float): [optional]  # noqa: E501
            distance_mid (float): [optional]  # noqa: E501
            distance_near (float): [optional]  # noqa: E501
            dn_left (float): [optional]  # noqa: E501
            dn_right (float): [optional]  # noqa: E501
            end_date (date): [optional]  # noqa: E501
            facet_form (str): [optional]  # noqa: E501
            form_height (float): [optional]  # noqa: E501
            form_length (float): [optional]  # noqa: E501
            frame (ArticleItem): [optional]  # noqa: E501
            frame_fit (float): [optional]  # noqa: E501
            frame_text (str): [optional]  # noqa: E501
            glas_left (GlassesConfiguration): [optional]  # noqa: E501
            glas_right (GlassesConfiguration): [optional]  # noqa: E501
            glasses_pass_printed (bool): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            initials (str): [optional]  # noqa: E501
            insets_left (float): [optional]  # noqa: E501
            insets_right (float): [optional]  # noqa: E501
            invoices ([Invoice]): [optional]  # noqa: E501
            komplettbrille (bool): [optional]  # noqa: E501
            mindestranddicke (float): [optional]  # noqa: E501
            modified (datetime): [optional]  # noqa: E501
            my_style_code (str): [optional]  # noqa: E501
            near_profile (str): [optional]  # noqa: E501
            near_vision_behaviour (str): [optional]  # noqa: E501
            notice (str): [optional]  # noqa: E501
            order_glasses (bool): [optional]  # noqa: E501
            ordered_glas_left (GlassesConfiguration): [optional]  # noqa: E501
            ordered_glas_right (GlassesConfiguration): [optional]  # noqa: E501
            own_frame (bool): [optional]  # noqa: E501
            price_frame (float): [optional]  # noqa: E501
            price_glas_left (float): [optional]  # noqa: E501
            price_glas_right (float): [optional]  # noqa: E501
            progression_length_left (float): [optional]  # noqa: E501
            progression_length_right (float): [optional]  # noqa: E501
            refraction_glasses (RefractionReport): [optional]  # noqa: E501
            refraction_objective (RefractionReport): [optional]  # noqa: E501
            refraction_prescription (RefractionReport): [optional]  # noqa: E501
            remote_edging (bool): [optional]  # noqa: E501
            scheibenwinkel (float): [optional]  # noqa: E501
            staff (StaffReduced): [optional]  # noqa: E501
            start_date (date): [optional]  # noqa: E501
            treatment (Treatment): [optional]  # noqa: E501
            treatment_head_id (str): [optional]  # noqa: E501
            treatment_number (str): [optional]  # noqa: E501
            type (PredefinedPropertyReduced): [optional]  # noqa: E501
            vorneigung (float): [optional]  # noqa: E501
            weight (float): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
